name=STX 2xBME280 Bosch Wrapper
version=1.0.0
author=SimpleTronix
maintainer=SimpleTronix
sentence=Reads two BME280 sensors on I2C 0x76 & 0x77 using Bosch BME280 library code.
paragraph=Self-Contained.  Includes Bosch BME280 library files.  Compatible with the SimpleTronix 2xBME280 board or any two BME280 modules.
category=Sensors
url=https://www.SimpleTronix.com
architectures=*
depends=
