name=STX 2xBME680 Zanshin Wrapper
version=1.0.0
author=SimpleTronix
maintainer=SimpleTronix
sentence=Reads two BME680 sensors on I2C 0x76 & 0x77 using Adafruit BME680 library code.
paragraph=Self-Contained.  Includes Zanshin BME680 library files.  Compatible with the SimpleTronix 2xBME680 board or any two BME680 modules.
category=Sensors
url=https://www.SimpleTronix.com
architectures=*
depends=
